import os
import torch
from typing import Tuple, Dict, Optional, List
from torch_geometric.data import Data, InMemoryDataset
from torch_geometric.loader import DataLoader

class DrugOODDataset(InMemoryDataset):
    """
    Custom PyG InMemoryDataset for DrugOOD-IC50.
    Loads the pre-processed .pt files generated by the official DrugOOD pipeline.
    """
    def __init__(self, root: str, split: str = 'train', split_type: str = 'scaffold', transform=None, pre_transform=None):
        self.split = split
        self.split_type = split_type
        super().__init__(root, transform, pre_transform)
        
        # Official DrugOOD saves files like: drugood_ic50_scaffold_train.pt
        fname = f"drugood_ic50_{self.split_type}_{self.split}.pt"
        self.data_path = os.path.join(self.processed_dir, fname)
        
        if not os.path.exists(self.data_path):
            raise FileNotFoundError(f"Processed file not found: {self.data_path}. "
                                    "Please ensure the official DrugOOD pipeline has processed the data.")
        
        self.data, self.slices = torch.load(self.data_path, weights_only=False)

    @property
    def processed_dir(self) -> str:
        return os.path.join(self.root, 'drugood', 'processed')

    @property
    def processed_file_names(self) -> List[str]:
        return [f"drugood_ic50_{st}_{sp}.pt" for st in ['scaffold', 'assay'] for sp in ['train', 'val', 'test']]

    def process(self):
        pass # Data is assumed to be pre-processed by the official DrugOOD repository


class BaseDrugOODLoader:
    """
    Base Object-Oriented Loader for DrugOOD datasets.
    
    This class encapsulates the data loading, splitting, and preprocessing logic 
    required for the TopoCID framework. It ensures that environment labels (E), 
    initial topological filtration weights (w), and structural validity flags (C(G)) 
    are correctly extracted and attached to the graph data objects.
    """

    def __init__(self, root: str, task: str = 'ic50', split_type: str = 'scaffold', batch_size: int = 128):
        """
        Initializes the DrugOOD dataset loader.
        
        Args:
            root (str): Root directory where the dataset is stored (/home/phd/datasets/).
            task (str): The specific DrugOOD task ('ic50').
            split_type (str): The OOD split type ('scaffold' or 'assay').
            batch_size (int): Batch size for the PyG DataLoaders.
        """
        self.root = root
        self.task = task
        self.split_type = split_type
        self.batch_size = batch_size
        
        os.makedirs(self.root, exist_ok=True)
        
        self.dataset_name = f"DrugOOD-{self.task.upper()}"
        self.datasets: Dict[str, InMemoryDataset] = {}

    def load_and_split(self) -> None:
        """
        Loads the train, val, and test splits for the specified task and split_type.
        """
        print(f"[{self.dataset_name}] Loading splits for '{self.split_type}' shift...")
        for split in ['train', 'val', 'test']:
            self.datasets[split] = DrugOODDataset(
                root=self.root, 
                split=split, 
                split_type=self.split_type
            )
            print(f"[{self.dataset_name}] Loaded {split} split: {len(self.datasets[split])} graphs.")

    def get_dataloaders(self) -> Tuple[DataLoader, DataLoader, DataLoader]:
        """
        Generates PyTorch Geometric DataLoaders for training, validation, and testing.
        
        Returns:
            Tuple[DataLoader, DataLoader, DataLoader]: Train, Val, and Test dataloaders.
        """
        if not self.datasets:
            raise RuntimeError("Dataset not loaded. Call load_and_split() first.")
        
        # Apply TopoCID-specific preprocessing to all splits
        for split in ['train', 'val', 'test']:
            self.datasets[split] = self._apply_topocid_preprocessing(self.datasets[split])
            
        train_loader = DataLoader(self.datasets['train'], batch_size=self.batch_size, shuffle=True)
        val_loader = DataLoader(self.datasets['val'], batch_size=self.batch_size, shuffle=False)
        test_loader = DataLoader(self.datasets['test'], batch_size=self.batch_size, shuffle=False)
        
        return train_loader, val_loader, test_loader

    def _apply_topocid_preprocessing(self, dataset: InMemoryDataset) -> InMemoryDataset:
        """
        Iterates through the dataset and attaches TopoCID-specific attributes:
        1. Environment labels (E) for Invariant Learning and TCD.
        2. Initial deterministic filtration weights (w) for the TDA layer.
        3. Structural validity flags (C(G)) for the SPCG constraint manifold.
        """
        for data in dataset:
            data = self._extract_environment_labels(data)
            data = self._initialize_filtration_weights(data)
            data = self._validate_structural_constraints(data)
        return dataset

    def _extract_environment_labels(self, data: Data) -> Data:
        """
        Extracts the discrete environment variable E_i for each graph.
        
        Mathematical Context (TopoCID - TCD Module):
        Ensures the conditional independence criterion Y \perp E | Z_topo can be 
        explicitly enforced during the Topological Contrastive Disentanglement phase.
        """
        if hasattr(data, 'env_id'):
            data.env = data.env_id
        elif hasattr(data, 'assay_id'): # DrugOOD specific attribute
            data.env = data.assay_id
        else:
            # Fallback if environment ID is not explicitly named
            data.env = torch.zeros(1, dtype=torch.long)
        return data

    def _initialize_filtration_weights(self, data: Data) -> Data:
        """
        Computes a deterministic initial scalar weight w(v) for each node to initialize 
        the simplicial filtration before the learnable MLP is applied.
        
        Mathematical Context (TopoCID - TCP Module):
        While the final weight is w(v) = u^T MLP(H^{(0)}_v), we initialize the filtration 
        using the L2 norm of the initial node features to ensure a deterministic, 
        non-random starting point for the clique complex Cl(G):
            w^{(0)}(v) = || H^{(0)}_v ||_2
        """
        if data.x is not None:
            # Compute L2 norm of node features as the deterministic initial weight
            data.filtration_weight = torch.norm(data.x.float(), p=2, dim=1)
        else:
            # Fallback to node degree if features are absent
            row, _ = data.edge_index
            deg = torch.zeros(data.num_nodes, dtype=torch.float)
            deg.scatter_add_(0, row, torch.ones_like(row, dtype=torch.float))
            data.filtration_weight = deg
        return data

    def _validate_structural_constraints(self, data: Data) -> Data:
        """
        Evaluates the structural constraint function C(G) for the SPCG module.
        
        Mathematical Context (TopoCID - SPCG Module):
        The valid data manifold M is defined as M = { G | C(G) = 0 }.
        For molecular graphs in DrugOOD, C(G) enforces chemical valency rules:
            sum_j A_ij <= v_type(i) for all nodes i.
        """
        data.is_valid = self._check_chemical_valency(data)
        return data

    def _check_chemical_valency(self, data: Data) -> bool:
        """
        Checks if the molecular graph satisfies chemical valency rules.
        This is critical for ensuring the SPCG module generates valid counterfactuals.
        """
        if data.edge_index is None or data.edge_index.numel() == 0:
            return True
            
        # Compute degrees for all nodes
        row, _ = data.edge_index
        degrees = torch.zeros(data.num_nodes, dtype=torch.long)
        degrees.scatter_add_(0, row, torch.ones_like(row, dtype=torch.long))
        
        # In organic chemistry (DrugOOD molecules), the maximum valid valency is 6 (for Sulfur).
        # If any node exceeds this physical limit, the graph is structurally invalid (C(G) != 0).
        max_valid_valency = 6 
        if torch.any(degrees > max_valid_valency):
            return False
            
        return True


class DrugOODIC50Loader(BaseDrugOODLoader):
    """
    Specific loader for the DrugOOD-IC50 dataset.
    Evaluates OOD generalization on binding affinity prediction under scaffold/assay shifts.
    """
    def __init__(self, root: str, split_type: str = 'scaffold', batch_size: int = 128):
        super().__init__(root, task='ic50', split_type=split_type, batch_size=batch_size)


# ==============================================================================
# Execution and Verification Block
# ==============================================================================
if __name__ == "__main__":
    # Strictly using the original dataset path as specified
    DATASET_ROOT = "/home/phd/datasets/"
    
    print("="*60)
    print("Initializing TopoCID Data Pipeline for DrugOOD-IC50")
    print("="*60)
    
    # 1. Load DrugOOD-IC50 (Scaffold Shift)
    print("\n--- Processing DrugOOD-IC50 (Scaffold Shift) ---")
    ic50_scaffold_loader = DrugOODIC50Loader(root=DATASET_ROOT, split_type='scaffold', batch_size=128)
    ic50_scaffold_loader.load_and_split()
    train_loader, val_loader, test_loader = ic50_scaffold_loader.get_dataloaders()
    
    # Verify a single batch from DrugOOD-IC50
    batch = next(iter(train_loader))
    print(f"Batch Graph Count: {batch.num_graphs}")
    print(f"Node Features Shape: {batch.x.shape}")
    print(f"Filtration Weights Shape: {batch.filtration_weight.shape}")
    print(f"Environment Labels Shape: {batch.env.shape}")
    print(f"Structural Validity (C(G)=0): {batch.is_valid.all().item()}")
    
    # 2. Load DrugOOD-IC50 (Assay Shift)
    print("\n--- Processing DrugOOD-IC50 (Assay Shift) ---")
    ic50_assay_loader = DrugOODIC50Loader(root=DATASET_ROOT, split_type='assay', batch_size=128)
    ic50_assay_loader.load_and_split()
    
    print("\n" + "="*60)
    print("Data Pipeline Verification Complete. No synthetic data used.")
    print("="*60)